const todos = [
  { 
    id: 1,
    category: 'Finance',
    title: 'File Bankruptcy at Upsolve',
    link: 'https://upsolve.org',
    selector: '',
    text: '',
    done: false,
    createdAt: 'Mar 03 2021 14:19:55 GMT+0530 (IST)',
  },
  { 
    id: 2,
    category: 'Jobs',
    title: 'Apply Job @usefluent',
    link: 'https://notion.so/Founding-Engineer-480e95c5a99649f4b0e0210eeb8c6600',
    selector: '',
    text: '',
    done: false,
    createdAt: 'Mon Apr 05 2019 14:19:55 GMT+0530 (IST)',
  },
  { 
    id: 3,
    category: 'Build',
    title: 'Finish the Devtools Pro Prototype design',
    link: 'https://dropbox.com/debdut/devtools-pro',
    selector: '',
    text: '',
    done: false,
    createdAt: 'Mon Apr 05 2021 14:19:55 GMT+0530 (IST)',
  },
  { 
    id: 4,
    category: 'Contact',
    title: 'Approach Pieter Levels for Devtools Pro @levelsio',
    link: 'https://twitter.com/levelsio',
    selector: '',
    text: '',
    done: false,
    createdAt: 'Mon Apr 05 2021 14:17:55 GMT+0530 (IST)',
  },
  { 
    id: 5,
    category: 'Movies',
    title: 'Watch Jobs Stanford Commencement Speech 2015',
    link: 'https://youtube.com/watch?v=UF8uR6Z6KLc',
    selector: '',
    text: "Drawing from some of the most pivotal points in his life, Steve Jobs, chief executive officer and co-founder of Apple Computer and of Pixar Animation Studios, urged graduates to pursue their dreams and see the opportunities in life's setbacks -- including death itself -- at the university's 114th Commencement on June 12, 2005.",
    done: false,
    createdAt: 'Mon Apr 05 2021 14:03:55 GMT+0530 (IST)',
  },
  { 
    id: 6,
    category: 'Build',
    title: 'Build Filter Table Feature like this',
    link: 'https://tryindex.com/beta',
    selector: 'body > div:nth-child(7) > div > div > div.content-width-small > h3 > strong',
    text: 'Filter & Highlight',
    done: false,
    createdAt: 'Mon Apr 05 2021 14:19:55 GMT+0530 (IST)',
  },
  { 
    id: 7,
    category: '',
    title: 'Build Waitlist on blogletter app',
    link: 'https://getwaitlist.com',
    selector: '#__next > div > div:nth-child(2) > div.HowTo___StyledDiv-sc-12fy97t-0.cCxvIF > div:nth-child(1) > div.HowTo___StyledDiv3-sc-12fy97t-2.YQuwC',
    text: 'Growth and Signups Users can sign up for your product and share their link wihttps://th friends. Reward them for successful referrals.',
    done: false,
    createdAt: 'Mon Mar 20 2021 14:19:55 GMT+0530 (IST)',
  },
  { 
    id: 8,
    category: '',
    title: 'Go to Grocery',
    done: false,
    createdAt: 'Mon Apr 05 2021 14:19:55 GMT+0530 (IST)',
  },
]

export default function Todos () {
  return todos
}